version: '3.4'

services:
  discordanimebot:
    image: discordanimebot
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 ./src/discord_bot_main.py "]
    ports:
      - 5678:5678
    env_file:
      - .env
    volumes:
      - ./data:/app/data

