gachi_dict = {
    "AAAAAAAH": "BillyH",
    "ATTEEEN-TION": "BillyH",
    "An ass I wouldn't mind fucking": "Brother",
    "Another victim": "BillyH",
    "Ass we can": "BillyH",
    "At least it smells like it": "BillyH",
    "Beat me 1 2 3": "MarkW",
    "Bet your ass": "BillyH",
    "Big surprise": "BillyH",
    "Boss of this gym": "MarkW",
    "Boy next door": "VanD",
    "Come on": "MarkW",
    "Come on college boy": "BillyH",
    "Deep dark fantasies": "VanD",
    "Do you like watching me": "babyface",
    "Do you like what you see": "VanD",
    "Dungeon master": "VanD",
    "FUCKYOU": "VanD",
    "Fisting is 300": "VanD",
    "Fuck you": "VanD",
    "Fuck you leather man": "MarkW",
    "Fucking cumming": "VanD",
    "Full master": "VanD",
    "Go another round": "MarkW",
    "I don't do anal": "VanD",
    "I love fire": "Brother",
    "I'm taking that ass": "BillyH",
    "It gets bigger when I pull": "Ripped",
    "It turns me on": "Brother",
    "It's a loan": "Brother",
    "It's bondage, gay website": "VanD",
    "It's macabre!": "Unripped",
    "It's so fucking deep": "VanD",
    "Jabroni outfit": "MarkW",
    "Knocked out some jabroni": "MarkW",
    "Ladies first": "BillyH",
    "Lash of the spanking": "BillyH",
    "Let's give it a go": "MarkW",
    "Like embarrassing me": "BillyH",
    "Lube it up": "VanD",
    "Mmmmh": "Unripped",
    "Oh Oh Aaah Ah": "Slave",
    "Oh ho ho ganging up": "Kazuya",
    "Oh my shoulder": "BillyH",
    "On the house": "babyface",
    "One more round": "BillyH",
    "Our daddy told us": "Ripped",
    "Penetration 1": "VanD",
    "Penetration 2": "VanD",
    "Penetration 3": "VanD",
    "Penetration 4": "VanD",
    "Performance artist": "VanD",
    "Playing with fire": "babyface",
    "Pull up our pants": "BillyH",
    "RIP ears": "babyface",
    "Right happy to": "Unripped",
    "Rip the skin": "Ripped",
    "Settle it": "MarkW",
    "She gave me quite a show": "babyface",
    "Shut the fuck up boy": "VanD",
    "Six hot loads": "BillyH",
    "Slaves get your ass back here": "VanD",
    "So how you feeling": "Kazuya",
    "Sorry": "Unripped",
    "Sorry for what": "Ripped",
    "Spank": "BillyH",
    "Spit - YEAAAH": "VanD",
    "Stick your finger": "VanD",
    "Suction": "VanD",
    "Swallow my cum": "VanD",
    "Take it boy": "VanD",
    "Thank you sir": "Slave",
    "That turns me on": "VanD",
    "That's amazing": "VanD",
    "That's power son": "BillyH",
    "The other night": "BillyH",
    "The point you wanna be": "BillyH",
    "The semen arsonist": "babyface",
    "Two can play it": "Kazuya",
    "WOO": "VanD",
    "What the hell are you two doing": "BillyH",
    "Why don't you get fucked": "babyface",
    "Without further interruption": "Unripped",
    "Work that tool": "BillyH",
    "Wrong door": "MarkW",
    "Yes sir": "Slave",
    "You can go now": "BillyH",
    "You get mad": "babyface",
    "You got me mad now": "BillyH",
    "You like challenges": "BillyH",
    "You like that": "BillyH",
    "You ripped my fucking pants": "BillyH",

}